export const {
    SIGEO_APP_PORT,
    SIGEO_SECRET_COOKIE,
    SIGEO_SECRET_JWT,
    SIGEO_DB_DATABASE,
    SIGEO_DB_USER,
    SIGEO_DB_PASSWORD,
    SIGEO_DB_HOST,
    SIGEO_DB_PORT,
    SIGEO_DB_DIALECT,
    SIGEO_DB_TIMEZONE
} = process.env;